version: '3.8'

services:
  database:
    image: 'postgres:latest'
    container_name: dm-postgres
    restart: always
    ports:
    - 5432:5432
    volumes:
    - ./db/:/var/lib/postgresql/data/
    env_file:
    - .env
volumes:
  db:
    driver: local
