version: '3.8'

services:
  database:
    image: 'postgres:latest'
    container_name: dm-postgres
    restart: always
    ports:
    - 5432:5432
    env_file:
    - .env
  minio:
    image: 'minio/minio'
    container_name: dm-minio
    restart: always
    ports:
    - 9000:9000
    - 9001:9001
    env_file:
    - .env
    command: server --console-address ":9001" /data
volumes:
  db:
    driver: local
