# Generated by Django 4.1.7 on 2023-03-06 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import dm_backend.enums.line_style_type


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Graph",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Equation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("equation", models.CharField(max_length=100)),
                ("parsed_equation", models.CharField(max_length=100)),
                ("color", models.IntegerField()),
                (
                    "line_style",
                    models.CharField(
                        choices=[
                            ("-", "SOLID"),
                            ("--", "DASHED"),
                            (":", "DOTTED"),
                            ("-.", "DASH_DOT"),
                        ],
                        default=dm_backend.enums.line_style_type.LineStyle["SOLID"],
                        max_length=5,
                    ),
                ),
                ("line_width", models.IntegerField()),
                (
                    "graph",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dm_backend.graph",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="graph",
            constraint=models.UniqueConstraint(
                fields=("name", "owner"), name="unique_graph_name"
            ),
        ),
    ]
