# Generated by Django 4.1.7 on 2023-03-24 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dm_backend", "0002_alter_equation_line_style"),
    ]

    operations = [
        migrations.AddField(
            model_name="graph",
            name="preview",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
