# Generated by Django 4.1.7 on 2023-04-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dm_backend", "0003_graph_preview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equation",
            name="line_style",
            field=models.CharField(
                choices=[("polyline", "SOLID"), ("scatter", "DOTTED")],
                default="polyline",
                max_length=8,
            ),
        ),
    ]
