# Generated by Django 4.1.7 on 2023-04-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dm_backend", "0004_alter_equation_line_style"),
    ]

    operations = [
        migrations.AlterField(
            model_name="graph",
            name="owner",
            field=models.CharField(max_length=255),
        ),
    ]
