# Generated by Django 4.1.7 on 2023-04-12 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dm_backend", "0005_alter_graph_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="graph",
            options={},
        ),
        migrations.RemoveConstraint(
            model_name="graph",
            name="unique_graph_name",
        ),
    ]
